#
# Module manifest for module 'vSphereTools'
#
# Generated by: jmedd
#
# Generated on: 24/02/2015
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = ''

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'b3b54c52-493a-4303-9152-a33fb727df68'

# Author of this module
Author = 'Jonathan Medd'

# Company or vendor of this module
CompanyName = 'Medd Inc'

# Copyright statement for this module
Copyright = 'Medd Inc'

# Description of the functionality provided by this module
Description = 'PowerCLI Tools'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = '2.0'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = ''

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = ''

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = 'PowerCLITools.Global.ps1','PowerCLITools.Initialise.ps1'

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules = 'Functions\Add-vCenterLicense.psm1',
				'Functions\Get-ClusterAverageCpuMemory.psm1',
				'Functions\Get-CurrentVIServer.psm1',
				'Functions\Get-SnapshotCreator.psm1',
				'Functions\Get-vCenterLicense.psm1',
				'Functions\Get-VMCreationDate.psm1',
				'Functions\Get-VMDiskData.psm1',
				'Functions\Get-VMHostAlarm.psm1',
				'Functions\Get-VMHostDumpCollector.psm1',
				'Functions\Get-VMHostiSCSIBinding.psm1',
				'Functions\Get-VMHostLicense.psm1',
				'Functions\Get-VMHostNetworkAdapterCDP.psm1',
				'Functions\Get-VMHostSyslogConfig.psm1',
				'Functions\Get-VMIPAddressFromNetwork.psm1',
				'Functions\Get-VMSCSIID.psm1',
				'Functions\Install-vSphereClient.psm1',
				'Functions\Install-vSpherePowerCLI.psm1',
				'Functions\New-vCenterPermission.psm1',
				'Functions\New-vCenterRole.psm1',
				'Functions\New-VMFromSnapshot.psm1',
				'Functions\Remove-vCenterLicense.psm1',
				'Functions\Set-VMHostDumpCollector.psm1',
				'Functions\Set-VMHostiSCSIBinding.psm1',
				'Functions\Set-VMHostLicense.psm1',
				'Functions\Set-VMHostSyslogConfig.psm1',
				'Functions\Set-VMHostToCurrentDateAndTime.psm1',
				'Functions\Test-VIServerConnection.psm1',
				'Functions\Update-ESXiSSL.psm1',
				'Functions\Update-VMNotesWithOwner.psm1',
				'Functions\Update-VMScsiDeviceOrder.psm1'

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''

}

